spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace    # 파라미터들을 볼 수 있다.
