-- create table catalog (
--     id bigint generated by default as identity,
--     created_at timestamp default CURRENT_TIMESTAMP not null,
--     product_id varchar(120) not null,
--     product_name varchar(255) not null,
--     stock integer not null,
--     unit_price integer not null,
--     primary key (id)
-- );
--
-- alter table catalog add constraint UK_9gggyslu2usn0rxs32mf055wq unique (product_id);

insert into catalog(product_id, product_name, stock, unit_price)
values('CATALOG-001', 'Berlin', 100, 1500);

insert into catalog(product_id, product_name, stock, unit_price)
values('CATALOG-002', 'Tokyo', 110, 1000);

insert into catalog(product_id, product_name, stock, unit_price)
values('CATALOG-003', 'Stockholm', 120, 2000);