spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true   # jpql 확인 가능 옵션
#        show_sql: true

logging.level:
    org.hibernate.SQL: debug